### ISSUE TITLE
Images not found: Assets naming issue vs. color array names issue.

### ISSUE THREAD

**Issue by revomediarepo** [peterfriese/Colors#1]
There is a mismatch between the color assets naming, which are in lowercase in the folder, ex. red, green, blue, etc and the color array which has the first letter capitalized, ex. Red, Green, Blue, etc.

This causes the color not to be found and no images are displayed.

**In ContentView.swift**
struct ContentView: View {
var colors = ["Red", "Green", "Yellow", "Blue", "Pink", "Purple"]
...

It should be 
var colors = ["red", "green", "yellow", "blue", "pink", "purple"]

<img width="500" alt="Screen Shot 2020-10-22 at 4 13 20 PM" src="https://user-images.githubusercontent.com/12749771/96927182-b03da280-1484-11eb-9bb9-b2d5ca7997d6.png">

Also, when you run in the terminal, use the new lowercase convention for colors.
$xcrun simctl openurl booted colors://green

-Best,
Mic Capota
Revo Media LLC

**Comment by peterfriese** [comment]
Thanks for reporting this and helping me to fix it, Mic!

**Comment by revomediarepo** [comment]
> Thanks for reporting this and helping me to fix it, Mic!

Peter, glad I was able to help!
--Mic
